### PR TITLE
Remove defaults

### LINKED ISSUE #34: ideas on default-values
The original idea behind default-values was to assist users/teammembers to quickly start using your project; an error with a long list of missing ENV-variables is not really welcoming.
Also, with default-values you give your users an example what would be an acceptable value.

The downside of default-values is that it's an abstraction that easily breaks: you might shield the user from having to worry about env-variables, but now the user might run into things like redis not running on the default-url you set etc. An error which is probably more cryptic and which requires the user to start looking where this value actually comes from.

The provided values only reach so far: giving variable `A` a default-value, results in `ENVied.A` having a value, not `ENV['A']` - so your application is using it, but the project's dependencies can't.

Another source of confusion with default-values is whether to provide the defined type, or a string (as is necessary when you disable defaults and have to use the ENV).

## sample-file

So, with the original motivation of 'easily bootstrap' in mind, how about another implementation, namely to generate an example file that can be sourced in the shell, e.g.:

```bash
# file: env.sample
export DATABASE_URL= # e.g. postgres://user:pw@localhost/database
export REDIS_URL=redis://localhost:6379
```

The following might be the Envfile that generated this:
```
variable :DATABASE_URL, :string, sample_desc: "e.g. postgres://user:pw@localhost/database"
variable :REDIS_URL,    :string, sample_value: "redis://localhost:6379"
```

So we have an example value for `REDIS_URL` (where we would now use a default-value) and the database-variable that we expect to differ between setups and so it only has a description/hint.

A user should get the instruction to copy `env.sample` to `env`, provide the values and source it.

I see the following benefits:
* `ENVied.require` becomes simpler: check if env-values are present and coercible. No more evalling of default-blocks, checking whether defaults are enabled etc.
* make setting the env-variables an explicit step for the user - no way around this as this is the way that the app is configured. _ENVied won't be a possible source of values_.
* provide defaults/hints for the tools that help the user set the environment - and more importantly, for the tools that the user already knows to set the environment.
* an example shell-file can also be used as template in environments where you won't/should not use defaults
* you can provide default-values for `ENV['VARIABLE']` not only for `ENVied.VARIABLE`. The latter is only used by the code you write. The former is also used by dependencies (e.g. `RAILS_ENV`, `REDIS_URL` etc.)

## planning

I reckon fixing this before v1.0 might require some iterations/real-life-feedback (and so might delay that release). Though I think it's worth it as default-values are not 1.0-worthy.

## resources

A tool I now use for years to get my environment right is https://github.com/direnv/direnv. Highly recommended. It targets different shells with just bash-syntax - so it would help us not go overboard with all kinds of shell-specific-generators.

Thoughts welcome!

### PR DESCRIPTION
**Pull request by eval**
resolves #34

### CODE REVIEW

**Comment by javierjulio** [comment]
I'd like to get in #56 first (after some updates as I'm going to remove the example messages) and do a release with that so we have deprecation notices. That will make it much easier for users to take their defaults from `Envfile` to another tool e.g. dotenv.

This default removal should go out as a separate release. Did you still want that as a major version?

**Comment by eval** [comment]
@javierjulio I created the `0-9-releases`-branch for that. Indeed there should be a 0.9-release that shows deprecating-warnings for default-values and documents alternatives. For the latter I plan on adding some section to the README in another PR.

**Comment by javierjulio** [comment]
Yes I saw that but what I’ve done is an important change and should be reflected in the master branch. Otherwise it won’t be there which I don’t think is good. We should branch off once that’s in.

**Comment by eval** [comment]
@javierjulio please rebase #56 on this branch once you removed the default-value-deprecation stuff.

**Comment by javierjulio** [comment]
No I won’t because you’ve removed all defaults. I don’t understand what you are doing because we agreed to do the deprecation first into master, not the removal.

**Comment by eval** [comment]
The plan is to create 0.9.x-release from a branch that still has defaults. To start we can release the huge refactorings you did, and ideally the first release we make also has the deprecation-warnings (but not necessary): there's an rc ready for that.
In the meantime the master is free of default-values and new features can be build that don't need to take it into account.

**Comment by javierjulio** [comment]
I disagree with that change as I mentioned above. I also find it disrespectful for the work I’ve done. We could have gotten the deprecation and other improvements in first and then do the defaults removal. The approach is to do that through master and then push/pick to a release branch.

**Pull request merged**
