### PR TITLE
[chore] Relax rack dependency

### PR DESCRIPTION
**Pull request by chytreg**
I use the gem with rails 5 which works on rack 2.0 only

### CODE REVIEW

**Comment by swistaczek** [comment]
Hey @chytreg , please try to fix travis build.

**Comment by olleolleolle** [comment]
(That build error, isn't that transient? It ran 5 months ago, with your typical "network glitch" output.)

**Comment by chytreg** [comment]
Unfortunately, there is a problem with ruby version. Rack 2, requires >= 2.2.2
https://github.com/rack/rack/blob/master/rack.gemspec#L29
I'm not sure how to resolve this problem, any guide how to setup it properly would be useful.

**Comment by olleolleolle** [comment]
@chytreg perhaps this would help? http://guides.rubygems.org/specification-reference/#add_runtime_dependency

**Comment by chytreg** [comment]
The question is how to support new features for the older version. If we add runtime dependency this will be breaking change (only rack >=2, only ruby >=2.2.2). Probably we should release some major version of Envied WDYT, and adjust test runner to skip ruby versions prior than 2.2.2

**Comment by olleolleolle** [comment]
Let me suggest an `if` in the gemspec.

```ruby
if RUBY_VERSION < '2.2.2'
  spec.add_dependency "rack", "~> 1.4"
else
  spec.add_dependency "rack", ">= 1.4"
end
```

**Comment by javierjulio** [comment]
Would the suggestion [@mpalmer made](https://github.com/eval/envied/issues/19#issuecomment-217618028) which uses `< 3, >= 1.x` (I've seen this elsewhere for rack) be a better choice? If so I'd be happy to submit a PR to get this Rails 5 ready. Love Envied. ❤️

**Comment by chytreg** [comment]
@javierjulio & @mpalmer I've managed to make it work on any ruby version.
Should I squash my commits before the PR is going to be merged?

**Comment by chytreg** [comment]
FYI it's rebased and ready to merge

**Comment by javierjulio** [comment]
@chytreg thanks! @eval any chance this can get reviewed so Envied is Rails 5 ready?

**Comment by rtlong** [comment]
This is great! @eval, if you could get 'round to merging this, it would make my day!

**Comment by bradfeehan** [comment]
It'd be great to get this merged, or a list of remaining tasks to get it across the line. Thanks for this tool <3

**Comment by javierjulio** [comment]
I've asked @eval to consider a set of releases for Envied in #29 and offered to take ownership of getting them out if he wants. I included this PR as the first release to go out as a patch update. Other issues have been organized into new minor releases. I would love feedback from the rest of you.

**Comment by javierjulio** [comment]
Thanks so much for doing this @chytreg! ❤️

**Pull request merged**
