### PR TITLE
Support heroku config --json ONLY

### LINKED ISSUE #41: envied check:heroku does not support multiline environment variables
Because Heroku config vars are [split by newlines](https://github.com/eval/envied/blob/master/lib/envied/cli.rb#L105), environment variables containing newlines cause the `envied check:heroku` task to raise an `ArgumentError`.

Perhaps a solution is to support `heroku config --json`, and parse the json instead of supporting the raw `heroku config`

### PR DESCRIPTION
**Pull request by jonahwh**
Fixes #41

### CODE REVIEW

**Comment by jonahwh** [comment]
How do you feel about this solution, vs a separate task or flag to support the json format?

**Comment by javierjulio** [comment]
@jonahwh I think this is a great solution as its much cleaner and simpler to parse JSON.

**Comment by javierjulio** [comment]
@jonahwh thanks for your contribution! ❤️

**Comment by javierjulio** [comment]
I've pushed out a 0.9.1 release with this change.

**Pull request merged**
