### PR TITLE
Support multiple groups

### LINKED ISSUE #15: Support multiple groups
Hey! Great gem, this has been really helpful for us. It would be nice to support multiple groups, like in a Gemfile:

``` ruby
group :staging, :production do
   variable :API_URL
end
```

### PR DESCRIPTION
**Pull request by alcesleo**
Apparently this was really easy. Fixes #15

### CODE REVIEW

**Comment by lexi-lambda** [comment]
Any reason this hasn't been merged in yet?

**Comment by javierjulio** [comment]
Thanks @alcesleo! ❤️

**Comment by alcesleo** [comment]
Happy to help! Glad to see this finally get merged :-)

**Comment by javierjulio** [comment]
No problem. Plan is to get this out for 0.9.0 release with some other changes. The changelog is being updated in master so you can see what it will include. Thanks again!

**Comment by alcesleo** [comment]
Great to hear! Thank you!

**Pull request merged**
